In [1]:
import numpy as np

In [4]:
a = np.zeros((8, 8), dtype=int)

a[1::2, ::2] = 1
a[::2, 1::2] = 1
a

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [10]:
a = np.zeros((5, 5), dtype=int) + np.arange(5)
a

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [12]:
a = np.random.random((3, 3, 3))
a

array([[[0.19125866, 0.45392828, 0.63849411],
        [0.33075384, 0.17867953, 0.97923386],
        [0.78743923, 0.1741418 , 0.13196238]],

       [[0.34384352, 0.7045928 , 0.50387885],
        [0.65444307, 0.62631769, 0.62543671],
        [0.39121359, 0.32295308, 0.90987751]],

       [[0.1245407 , 0.60397302, 0.66374917],
        [0.66111617, 0.59605594, 0.53661884],
        [0.47498436, 0.04459574, 0.8525826 ]]])

In [17]:
a = np.ones((5, 5), dtype=int)
a[1:4, 1:4] = 0
a

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])

In [36]:
a = np.random.randint(0, 20, 8)
a.sort()
a[::-1]

array([18, 17, 16, 15, 12, 10,  7,  2], dtype=int32)

In [44]:
a = np.random.random((5, 5))
print(a.shape)
print(a.size)
print(a.itemsize)
print(a.ndim)

(5, 5)
25
8
2

In [46]:
import pandas as pd

s1 = pd.Series([1, 2, 3, 4, 5])
s2 = pd.Series([5, 4, 3, 2, 1])
d = np.sqrt(sum((s1 - s2) ** 2))
d

np.float64(6.324555320336759)

In [51]:
dataframe = pd.read_csv('baseball.csv')
dataframe.head()

,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,salary
0,0.271,0.328,74,161,22,6,12,58,49,133,23,17,1,1,0,0,109
1,0.264,0.318,24,48,7,0,1,22,15,18,0,7,0,0,0,0,160
2,0.251,0.338,101,141,35,3,32,105,71,104,34,6,0,0,1,0,2700
3,0.224,0.274,28,94,21,1,1,44,27,54,2,7,1,1,0,0,550
4,0.206,0.262,14,51,18,1,1,28,17,26,0,3,1,1,0,0,300

In [56]:
dataframe.head(2)

,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,salary
0,0.271,0.328,74,161,22,6,12,58,49,133,23,17,1,1,0,0,109
1,0.264,0.318,24,48,7,0,1,22,15,18,0,7,0,0,0,0,160

In [53]:
dataframe.tail(3)

,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,salary
334,0.208,0.265,12,35,11,1,0,15,14,30,2,6,0,0,0,0,365
335,0.290,0.349,59,141,30,2,16,64,42,102,14,6,1,0,0,0,990
336,0.225,0.312,37,64,12,0,17,48,36,80,1,0,1,0,0,0,2167

In [54]:
dataframe.shape

(337, 17)

In [55]:
dataframe.describe()

,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,salary
count,337.000000,337.000000,337.000000,337.000000,337.000000,337.000000,337.000000,337.000000,337.000000,337.000000,337.000000,337.000000,337.000000,337.000000,337.000000,337.000000,337.000000
mean,0.257825,0.323973,46.697329,92.833828,16.673591,2.338279,9.097923,44.020772,35.017804,56.706231,8.246291,6.771513,0.397626,0.115727,0.192878,0.029674,1248.528190
std,0.039546,0.047132,29.020166,51.896322,10.452001,2.543336,9.289934,29.559406,24.842474,33.828784,11.664782,5.927490,0.490135,0.320373,0.395145,0.169938,1240.013309
min,0.063000,0.063000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,109.000000
25%,0.238000,0.297000,22.000000,51.000000,9.000000,0.000000,2.000000,21.000000,15.000000,31.000000,1.000000,3.000000,0.000000,0.000000,0.000000,0.000000,230.000000
50%,0.260000,0.323000,41.000000,91.000000,15.000000,2.000000,6.000000,39.000000,30.000000,49.000000,4.000000,5.000000,0.000000,0.000000,0.000000,0.000000,740.000000
75%,0.281000,0.354000,69.000000,136.000000,23.000000,3.000000,15.000000,66.000000,49.000000,78.000000,11.000000,9.000000,1.000000,0.000000,0.000000,0.000000,2150.000000
max,0.457000,0.486000,133.000000,216.000000,49.000000,15.000000,44.000000,133.000000,138.000000,175.000000,76.000000,31.000000,1.000000,1.000000,1.000000,1.000000,6100.000000

In [57]:
dataframe.iloc[1:4]

,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,salary
1,0.264,0.318,24,48,7,0,1,22,15,18,0,7,0,0,0,0,160
2,0.251,0.338,101,141,35,3,32,105,71,104,34,6,0,0,1,0,2700
3,0.224,0.274,28,94,21,1,1,44,27,54,2,7,1,1,0,0,550

In [58]:
dataframe[dataframe['5'] <= 30].head(2)

,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,salary
0,0.271,0.328,74,161,22,6,12,58,49,133,23,17,1,1,0,0,109
1,0.264,0.318,24,48,7,0,1,22,15,18,0,7,0,0,0,0,160

In [59]:
url = 'https://raw.githubusercontent.com/akmand/datasets/master/iris.csv'
dataframe = pd.read_csv(url)
dataframe

,sepal_length_cm,sepal_width_cm,petal_length_cm,petal_width_cm,species
0,5.1,3.5,1.4,0.2,setosa
1,4.9,3.0,1.4,0.2,setosa
2,4.7,3.2,1.3,0.2,setosa
3,4.6,3.1,1.5,0.2,setosa
4,5.0,3.6,1.4,0.2,setosa
...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,virginica
146,6.3,2.5,5.0,1.9,virginica
147,6.5,3.0,5.2,2.0,virginica
148,6.2,3.4,5.4,2.3,virginica
149,5.9,3.0,5.1,1.8,virginica

In [61]:
from sklearn import preprocessing
scaler1 = preprocessing.MinMaxScaler()
dataframe['sepal_length_cm'] = scaler1.fit_transform(dataframe[['sepal_length_cm']])
scaler2 = preprocessing.StandardScaler()
dataframe['sepal_width_cm'] = scaler2.fit_transform(dataframe[['sepal_width_cm']])
dataframe

,sepal_length_cm,sepal_width_cm,petal_length_cm,petal_width_cm,species
0,0.222222,1.032057,1.4,0.2,setosa
1,0.166667,-0.124958,1.4,0.2,setosa
2,0.111111,0.337848,1.3,0.2,setosa
3,0.083333,0.106445,1.5,0.2,setosa
4,0.194444,1.263460,1.4,0.2,setosa
...,...,...,...,...,...
145,0.666667,-0.124958,5.2,2.3,virginica
146,0.555556,-1.281972,5.0,1.9,virginica
147,0.611111,-0.124958,5.2,2.0,virginica
148,0.527778,0.800654,5.4,2.3,virginica
149,0.444444,-0.124958,5.1,1.8,virginica